version: '3'
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: orad
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/orad
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  data: